name: riverpod_infinite_scroll_pagination
description: An infinite scroll pagination using Riverpod (Lazy loading pages as
  the user scrolls to the end of the list).
version: 1.0.4
homepage: https://github.com/hafees/riverpod_infinite_scroll
repository: https://github.com/hafees/riverpod_infinite_scroll
issue_tracker: https://github.com/hafees/riverpod_infinite_scroll/issues

topics:
  - riverpod
  - pagination
  - scrolling-pagination
  - infinite-scroll-pagination

environment:
  sdk: ">=3.1.2 <4.0.0"

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.0-dev.3
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.4
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  envied_generator: ^0.5.4+1
  freezed: ^2.4.5
  json_serializable: ^6.8.0
  mocktail: ^1.0.1
  test: ^1.24.3
  very_good_analysis: ^6.0.0